# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import berkeley_pb2 as berkeley__pb2


class ClockSyncStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncTime = channel.unary_unary(
                '/berkeley.ClockSync/SyncTime',
                request_serializer=berkeley__pb2.TimeRequest.SerializeToString,
                response_deserializer=berkeley__pb2.TimeResponse.FromString,
                )


class ClockSyncServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClockSyncServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncTime,
                    request_deserializer=berkeley__pb2.TimeRequest.FromString,
                    response_serializer=berkeley__pb2.TimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'berkeley.ClockSync', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClockSync(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/berkeley.ClockSync/SyncTime',
            berkeley__pb2.TimeRequest.SerializeToString,
            berkeley__pb2.TimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
