# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: berkeley.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x65rkeley.proto\x12\x08\x62\x65rkeley\"\"\n\x0bTimeRequest\x12\x13\n\x0b\x63lient_time\x18\x01 \x01(\x03\"6\n\x0cTimeResponse\x12\x13\n\x0bserver_time\x18\x01 \x01(\x03\x12\x11\n\ttime_diff\x18\x02 \x01(\x03\x32H\n\tClockSync\x12;\n\x08SyncTime\x12\x15.berkeley.TimeRequest\x1a\x16.berkeley.TimeResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'berkeley_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEREQUEST._serialized_start=28
  _TIMEREQUEST._serialized_end=62
  _TIMERESPONSE._serialized_start=64
  _TIMERESPONSE._serialized_end=118
  _CLOCKSYNC._serialized_start=120
  _CLOCKSYNC._serialized_end=192
# @@protoc_insertion_point(module_scope)
